### ISSUE TITLE
Error setting machine configuration from flags provided: gob: name not registered for interface: "*rpcdriver.RpcFlags"

### ISSUE THREAD

**Issue by kyasu1** [yamamoto-febc/docker-machine-sakuracloud#11]
下記のエラーが出てしまいます。
Error setting machine configuration from flags provided: gob: name not registered for interface: "*rpcdriver.RpcFlags"

環境は下記のとおりです。
go version go1.5.2 darwin/amd64
docker-machine version 0.5.0 (04cfa58)
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50

**Comment by yamamoto-febc** [comment]
docker-machine 0.5.0であることと、エラーの内容が"RpcFlags"が見つからないというものであることから、おそらくdocker-machineの以下のIssueが該当するかと思います。

[Docker Machine v0.5.1 breaks compatibility with v0.5.0 drivers](https://github.com/docker/machine/issues/2325)

docker-machine本体側バージョン0.5.1(具体的にはこの[コミット](https://github.com/docker/machine/commit/89d9854943dfade25abd9135d7065c5b0ae04353))で"Rpc"を"RPC"とする命名変更が行われたことで、この変更後にビルド(リンク)されたプラグインは0.5.0以前のバージョンでは利用できなくなりました。
docker-machine-sakuracloudではv0.0.5以降のバージョンが該当します。

docker-machineを0.5.1以降にバージョンアップすれば解決するかと思います。

**Comment by kyasu1** [comment]
早速のご回答ありがとうございます。

DockerToolboxをインストールし直して

docker-machine version 0.5.4, build 6643d0e

としたところ、エラーも出ず正常に作成が完了しました。
ありがとうございました。
