### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by yamamoto-febc** [yamamoto-febc/docker-machine-sakuracloud#2]
OS : Windows Server 2012 R2 on SAKURA CLOUD

Get an error such as the following when you run on Windows
```console
WARNING >>> Error starting plugin binary: fork/exec C:\Program Files\Docker Toolbox\docker-machine-driver-sakuracloud.exe: This version ...
```

**Comment by dalicejp** [comment]
C:\>docker-machine -v
docker-machine version 0.5.0 (04cfa58)

C:\>docker-machine create --driver sakuracloud
WARNING >>> Error starting plugin binary: fork/exec C:\Program Files\Docker Toolbox\docker-machine-driver-sakuracloud.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Error loading driver "sakuracloud": Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

**Comment by yamamoto-febc** [comment]
It was repared by re-build. 
(alt. リビルドで直りました。パッケージングミスでした、、) sorry!

![sakura_windows](https://cloud.githubusercontent.com/assets/1644816/11090918/72391124-88b9-11e5-9176-419d5c8b4c55.png)
